"use client";

import { motion } from "framer-motion";

const ITINERARY = [
  { time: "14:00", title: "Check-in at hotel (near Lusail)", icon: "🏨", note: "Drop bags, grab metro card" },
  { time: "15:30", title: "Souq district food tour", icon: "🍢", note: "Local cuisine, 20 min by metro" },
  { time: "17:00", title: "Stadium shuttle to Gate D", icon: "🚌", note: "Free with match ticket" },
  { time: "18:00", title: "Fan zone & security screening", icon: "🎟️", note: "Gates open 3h before kickoff" },
  { time: "20:00", title: "Morocco vs Portugal — Final", icon: "⚽", note: "Seat Block 12, Gate D access" },
  { time: "22:30", title: "Post-match metro (extended hrs)", icon: "🚇", note: "Runs until 02:00" },
];

export default function FanDashboard() {
  return (
    <main className="max-w-3xl mx-auto px-6 py-10">
      <motion.h1 initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="font-display text-3xl">
        Fan Dashboard
      </motion.h1>
      <p className="text-white/50 mt-2">
        Personalized for <span className="text-brand-glow">Morocco</span> supporter · Hotel near
        Lusail · Budget: moderate
      </p>

      <div className="mt-8 space-y-3">
        {ITINERARY.map((it, i) => (
          <motion.div
            key={i}
            initial={{ opacity: 0, x: -10 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: i * 0.05 }}
            className="glass rounded-2xl p-4 flex items-center gap-4"
          >
            <div className="text-2xl">{it.icon}</div>
            <div className="flex-1">
              <div className="font-semibold">{it.title}</div>
              <div className="text-xs text-white/50">{it.note}</div>
            </div>
            <div className="text-sm text-brand-glow font-display">{it.time}</div>
          </motion.div>
        ))}
      </div>
      <p className="text-[11px] text-white/30 mt-6">
        Itinerary generated by the Fan Agent (demo data).
      </p>
    </main>
  );
}
